### PR TITLE
made library swift 3 compatible

### LINKED ISSUE #6: Swift3
Any plan for a Swift3 migration ?

Tried with Xcode8 --> Convert syntax to Swift 3 and works like magic.
It will be a matter of uploading new code.

### PR DESCRIPTION
**Pull request by ozgur**
Made the library Swift3 compatible. This also resolves https://github.com/me-abhinav/NumberMorphView/issues/6.

PTAL @me-abhinav

### CODE REVIEW

**Comment by me-abhinav** [comment]
Hey @ozgur Thanks for the pull request 👍
I noticed that travis build is failing. Can you please fix that?

**Comment by ozgur** [comment]
@me-abhinav it looks your travis config is using a fairly old pod version which is **0.38** and Xcode 7.3. For it to work, I should update them to **1.0.1** and **8.2.1** respectively.

**Comment by me-abhinav** [comment]
@ozgur Yes. Actually the travis config and migration to swift 3 has to be done at the same time. Could you please change the travis file?

**Comment by ozgur** [comment]
@me-abhinav it looks like xctool is not compatible with Xcode8 and Facebook doesn't have plans to fix that for now. I am bypassing it by building and testing with the built-in xcodebuild command.

https://github.com/facebook/xctool/issues/704 

https://github.com/travis-ci/travis-ci/issues/6251

**Pull request merged**
