### PR TITLE
Update to Swift 2.2

### PR DESCRIPTION
**Pull request by albinekcom**
This commit fixes 2 warnings: "Use '#selector' instead of explicitly constructing a 'Selector'".

### CODE REVIEW

**Comment by me-abhinav** [comment]
@albinekcom Travis build is failing for this pull request. Can you please try with `osx_image: xcode7.3` and `xcode_sdk: iphonesimulator9.3`?

**Comment by albinekcom** [comment]
I noticed travis-ci after opening Pull Request. I have fixed it and I have also updated information in `README.md` file.

**Comment by me-abhinav** [comment]
There seems to be some problem with travis now. I referred this: [https://github.com/travis-ci/travis-ci/issues/3986](https://github.com/travis-ci/travis-ci/issues/3986) Seems like problem is with `osx_image: xcode7.3`

**Comment by albinekcom** [comment]
Try to rebuild. Maybe it will build this time...

**Comment by me-abhinav** [comment]
I rebuilt it several times since yesterday. Now some other problem is happening. I hope it will get resolved in some time. I will wait till then :)

**Comment by me-abhinav** [comment]
@albinekcom
Can you please add following code to the .yml?
`before_install:
    - brew uninstall xctool && brew install --HEAD xctool`
The travis build will pass and I will merge this request. You can refer [this](https://github.com/me-abhinav/NumberMorphView/blob/dev/.travis.yml).

**Pull request merged**
